### ISSUE TITLE
2 small issues

### ISSUE THREAD

**Issue by ghost** [ytisf/muninn#1]
Hey man, Awesome tool, certainly helps with my initial triage of memory samples so thanks for writing it.

I found 2 small things that gave an error when running it initially. Once the vol.py path is set and it begins the assessment i received the following error
    Traceback (most recent call last):
      File "/PATH/./muninn.py", line 133, in <module>
        doc.InitiateDocument(casenumber, date, filename, vol._md5sum, vol._image_type)		# Generate     document template
  File "/PATH/imports/report_manager.py", line 46, in InitiateDocument
    curr_filename = self.get_file_name(casenumber)
  File "/PATH/imports/report_manager.py", line 31, in get_file_name
    **return "CS" + str(case_num) + "-" + number + ".txt"**

So within the file report_manager.py on line 31 was the statement "return "CS" + str(case_num) + "-" + number + ".txt""  which i suspect python was interpreting number as an actual integer given thats the name i gave my report, i changed that line to 

**"return "CS" + str(case_num) + "-" + str(number) + ".txt" "**

Then that error was resolved.

The next error i received was 

Traceback (most recent call last):
  File "/PATH/./muninn.py", line 154, in <module>
    doc.pri
**AttributeError: Secretary instance has no attribute 'pri'**

So navigating to that statement it seemed it wasnt finished and wasnt calling any specific method so i just commented it out as the statements above and below it seemed to be fine.

Then the tool worked fine and i received the output i expected from it.

Awesome tool and just wanted to give some feedback. Thanks!

**Comment by ytisf** [comment]
Thanks for the update. 
Issues are now fixed 👍
